job:
  image: hmctspublic.azurecr.io/payment/jobs:latest
  schedule: "0 0,0 8,9,10 ? * * *"
  environment:
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    PAYMENT_SERVER_URL: http://payment-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    ccpay:
      secrets:
        - gateway-s2s-client-id
        - gateway-s2s-client-secret
  aadIdentityName: ccpay
global:
  job:
    kind: CronJob
